sudo: false
language: node_js
node_js:
- 8.0.0
- 9.0.0
- 10.0.0
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- $TRAVIS_BUILD_DIR/.travis.d/install.sh
script:
- $TRAVIS_BUILD_DIR/.travis.d/tests.sh
