version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.5
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies
          keys:
            - deps-v1-{{ checksum "package-lock.json" }}
            - deps-v1-
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Test CLI
          command: bin/better-crowdin --version
      - save_cache:
          name: Save dependencies
          key: deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
